### PR TITLE
pull

### PR DESCRIPTION
**Pull request by pk2507**

### CODE REVIEW

**Comment by KaidenP** [comment]
Explain.

**Comment by pk2507** [comment]
cant u guys add it to cynogenmod  GitHub

**Comment by pk2507** [comment]
it will help device

**Comment by KaidenP** [comment]
This is an unofficial port, so cyanogenmod probably won't. Also, your pull request is from a different fone than the GT-S7650M.

**Comment by pk2507** [comment]
fuck u

**Pull request closed without merging**
